<a href="https://colab.research.google.com/github/KarthikRajan/GenAi/blob/main/Databricks_dolly_v2_3b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Model card: https://huggingface.co/databricks/dolly-v2-3b

In [ ]:
import torch
from transformers import pipeline

generate_text = pipeline(model="databricks/dolly-v2-3b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto")


A new version of the following files was downloaded from https://huggingface.co/databricks/dolly-v2-3b:
- instruct_pipeline.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


In [ ]:
res = generate_text("Explain to me the difference between nuclear fission and fusion.")
print(res[0]["generated_text"])

Nuclear fission creates a new atom by fusing two smaller ones together. This releases a lot of energy in the form of nuclear radiation. The resulting nucleus creates smaller nuclei, which leads to infinite nuclear chain reaction.

Nuclear fusion, on the other hand, creates a new atom by combining atoms of hydrogen or helium together. This releases less energy than nuclear fission, but yields much brighter light. Sunlight is mostly composed of nuclear fusion. Nuclear fusion releases energy in the form of light.


In [2]:
2 + 2

4

In [3]:
import torch

In [6]:
list_1 = [[1,2,3,4,5], [6,7,8,9]]
print(list_1)

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]


In [8]:
import numpy as np
np1 = np.random.rand(3,4)
print(np1)

[[0.52744155 0.78853267 0.44232515 0.33516091]
 [0.75932933 0.18362765 0.80133193 0.18844847]
 [0.12643609 0.82484802 0.26371907 0.03484793]]


In [9]:
tensor_2 = torch.randn(3,4,6)
tensor_2

tensor([[[ 1.3699e+00, -7.3464e-01,  9.2756e-01,  1.1967e+00,  2.0925e+00,
           4.2934e-01],
         [ 1.7704e-02, -6.1559e-03,  1.2769e+00,  5.2441e-01,  4.0814e-01,
          -4.4810e-01],
         [-7.0997e-01,  1.4069e+00,  2.2324e-01, -9.3536e-01, -3.4704e-01,
          -7.0852e-01],
         [ 9.6809e-01,  1.3273e-01, -1.0414e+00,  1.2909e-01, -1.7801e+00,
           2.0055e+00]],

        [[ 4.7077e-02,  2.6023e+00,  1.4840e+00, -1.3208e-01, -1.6507e-02,
          -5.0147e-01],
         [-3.0288e-01,  4.9434e-01, -1.9734e-01,  1.4361e-01,  1.4309e+00,
          -1.6509e+00],
         [-7.3983e-01,  7.4748e-01,  3.4002e+00,  7.3853e-01, -6.4195e-01,
          -8.0311e-01],
         [-8.4760e-01, -4.8531e-01,  1.7908e-02,  4.4138e-01,  8.8256e-01,
           1.7333e+00]],

        [[-2.8513e-01,  1.9446e-03, -1.8317e-01, -5.2941e-02,  1.2496e+00,
           6.1456e-01],
         [-1.8544e-01,  8.6746e-01,  9.6239e-01, -1.0051e+00, -2.7007e-01,
          -1.4718e+00],
      

TENSOR BASICS

In [11]:
new1 = torch.tensor(np1)
new1


tensor([[0.5274, 0.7885, 0.4423, 0.3352],
        [0.7593, 0.1836, 0.8013, 0.1884],
        [0.1264, 0.8248, 0.2637, 0.0348]], dtype=torch.float64)

TENSOR SLICE AND RESHAPE

In [29]:
tensor_1 = torch.arange(10)
tensor_1


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
tensor_1 = tensor_1.reshape(2,5)
tensor_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

if you are not sure of the list count  (-1) last element in the list

In [31]:
tensor_1 = tensor_1.reshape(2,-1)
tensor_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
tensor_3 = tensor_1.view(2,5)
tensor_3


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
tensor_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Option to update the data


In [37]:
tensor_3[1,3,] = 3464
tensor_3

tensor([[   0,    1,    2,    3,    4],
        [3464, 3464, 3464, 3464, 3464]])

SLICING

In [46]:
tensor_7 = torch.arange(10)
tensor_7
#tensor_7[5]


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

GLABBING DATA & ASSIGNING VALUE TO a LIST

In [51]:
tensor_7[2] = 45
tensor_7
#tensor_7 = tensor_7.reshape(2,2)
tensor_8 = tensor_7.reshape(2,5)
tensor_8[:1:]

tensor_8[2] = 55
tensor_8

IndexError: index 2 is out of bounds for dimension 0 with size 2

BASIC MATH OPERATION IN TENSOR